name: Pull request
on: pull_request

jobs:
  commitsar:
    runs-on: ubuntu-latest
    name: Verify commit messages
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run commitsar
        uses: docker://aevea/commitsar@sha256:27ea5e528b153393e924d98764d6400a181f03768d972ba151b3ddc9f14ff12c
