name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release-notes:
    name: Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Release Notary Action
        uses: docker://aevea/release-notary@sha256:03e771a509881121758b05217a8938ca8379d29dfa69a2605ceca06ffca2db4d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Package Registry
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          image: kaniko
          cache: true
          cache_registry: cache

      - name: Dockerhub
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: aevea/kaniko
          cache: true
          cache_registry: aevea/cache
